# -*- coding: utf-8 -*-
"""hw1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ACZZwPcEtguJSqPMrv6EsmY3HtBMo622
"""

#請求用戶輸入身高體重
height=float(input("請輸入您的身高(公尺):"))
weight=float(input("請輸入您的體重(公斤):"))
BMI=weight/(height**2)
print(f"您的BMI是:{BMI:.2f}")